import json
import re

institution_names = [
    "Bendahara Umum Negara (Kementerian Keuangan)",
    "Kementerian Koordinator Bidang Politik, Hukum, dan Keamanan",
    "Kementerian Koordinator Bidang Perekonomian",
    "Kementerian Koordinator Bidang Pembangunan Manusia dan Kebudayaan",
    "Kementerian Koordinator Bidang Kemaritiman dan Investasi",
    "Kementerian Sekretariat Negara",
    "Kementerian Dalam Negeri",
    "Kementerian Luar Negeri",
    "Kementerian Pertahanan",
    "Kementerian Hukum dan Hak Asasi Manusia",
    "Kementerian Keuangan",
    "Kementerian Energi dan Sumber Daya Mineral",
    "Kementerian Perindustrian",
    "Kementerian Perdagangan",
    "Kementerian Pertanian",
    "Kementerian Lingkungan Hidup dan Kehutanan",
    "Kementerian Perhubungan",
    "Kementerian Kelautan dan Perikanan",
    "Kementerian Ketenagakerjaan",
    "Kementerian Desa, Pembangunan Daerah Tertinggal, dan Transmigrasi",
    "Kementerian Pekerjaan Umum dan Perumahan Rakyat",
    "Kementerian Kesehatan",
    "Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi",
    "Kementerian Sosial",
    "Kementerian Agama",
    "Kementerian Pariwisata dan Ekonomi Kreatif",
    "Kementerian Komunikasi dan Informatika",
    "Kementerian Koperasi dan Usaha Kecil dan Menengah",
    "Kementerian Pemberdayaan Perempuan dan Perlindungan Anak",
    "Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi",
    "Kementerian Perencanaan Pembangunan Nasional/Badan Perencanaan Pembangunan Nasional",
    "Kementerian Badan Usaha Milik Negara",
    "Kementerian Investasi/Badan Koordinasi Penanaman Modal",
    "Kementerian Pemuda dan Olahraga",
    "Kejaksaan Republik Indonesia",
    "Kepolisian Negara Republik Indonesia",
    "Lembaga Penyiaran Publik Televisi Republik Indonesia",
    "Lembaga Penyiaran Publik Radio Republik Indonesia",
    "Mahkamah Agung",
    "Mahkamah Konstitusi",
    "Majelis Permusyawaratan Rakyat",
    "Otoritas Ibu Kota Nusantara",
    "Pemerintah Provinsi Aceh",
    "Pemerintah Provinsi Bali",
    "Pemerintah Provinsi Banten",
    "Pemerintah Provinsi Bengkulu",
    "Pemerintah Provinsi D.I. Yogyakarta",
    "Pemerintah Provinsi D.K.I. Jakarta",
    "Pemerintah Provinsi Gorontalo",
    "Pemerintah Provinsi Jambi",
    "Pemerintah Provinsi Jawa Barat",
    "Pemerintah Provinsi Jawa Tengah",
    "Pemerintah Provinsi Jawa Timur",
    "Pemerintah Provinsi Kalimantan Barat",
    "Pemerintah Provinsi Kalimantan Selatan",
    "Pemerintah Provinsi Kalimantan Tengah",
    "Pemerintah Provinsi Kalimantan Timur",
    "Pemerintah Provinsi Kalimantan Utara",
    "Pemerintah Provinsi Kepulauan Bangka Belitung",
    "Pemerintah Provinsi Kepulauan Riau",
    "Pemerintah Provinsi Lampung",
    "Pemerintah Provinsi Maluku",
    "Pemerintah Provinsi Maluku Utara",
    "Pemerintah Provinsi Nusa Tenggara Barat",
    "Pemerintah Provinsi Nusa Tenggara Timur",
    "Pemerintah Provinsi Papua",
    "Pemerintah Provinsi Papua Barat",
    "Pemerintah Provinsi Papua Barat Daya",
    "Pemerintah Provinsi Papua Pegunungan",
    "Pemerintah Provinsi Papua Selatan",
    "Pemerintah Provinsi Papua Tengah",
    "Pemerintah Provinsi Riau",
    "Pemerintah Provinsi Sulawesi Barat",
    "Pemerintah Provinsi Sulawesi Selatan",
    "Pemerintah Provinsi Sulawesi Tengah",
    "Pemerintah Provinsi Sulawesi Tenggara",
    "Pemerintah Provinsi Sulawesi Utara",
    "Pemerintah Provinsi Sumatera Barat",
    "Pemerintah Provinsi Sumatera Selatan",
    "Pemerintah Provinsi Sumatera Utara",
    "Pemerintah Kab. Aceh Barat",
    "Pemerintah Kab. Aceh Barat Daya",
    "Pemerintah Kab. Aceh Besar",
    "Pemerintah Kab. Aceh Jaya",
    "Pemerintah Kab. Aceh Selatan",
    "Pemerintah Kab. Aceh Singkil",
    "Pemerintah Kab. Aceh Tamiang",
    "Pemerintah Kab. Aceh Tengah",
    "Pemerintah Kab. Aceh Tenggara",
    "Pemerintah Kab. Aceh Timur",
    "Pemerintah Kab. Aceh Utara",
    "Pemerintah Kab. Agam",
    "Pemerintah Kab. Alor",
    "Pemerintah Kab. Asahan",
    "Pemerintah Kab. Asmat",
    "Pemerintah Kab. Badung",
    "Pemerintah Kab. Balangan",
    "Pemerintah Kab. Bandung",
    "Pemerintah Kab. Bandung Barat",
    "Pemerintah Kab. Banggai",
    "Pemerintah Kab. Banggai Kepulauan",
    "Pemerintah Kab. Banggai Laut",
    "Pemerintah Kab. Bangka",
    "Pemerintah Kab. Bangka Barat",
    "Pemerintah Kab. Bangka Selatan",
    "Pemerintah Kab. Bangka Tengah",
    "Pemerintah Kab. Bangkalan",
    "Pemerintah Kab. Bangli",
    "Pemerintah Kab. Banjar",
    "Pemerintah Kab. Banjarnegara",
    "Pemerintah Kab. Bantaeng",
    "Pemerintah Kab. Bantul",
    "Pemerintah Kab. Banyuasin",
    "Pemerintah Kab. Banyumas",
    "Pemerintah Kab. Banyuwangi",
    "Pemerintah Kab. Barito Kuala",
    "Pemerintah Kab. Barito Selatan",
    "Pemerintah Kab. Barito Timur",
    "Pemerintah Kab. Barito Utara",
    "Pemerintah Kab. Barru",
    "Pemerintah Kab. Batang",
    "Pemerintah Kab. Batanghari",
    "Pemerintah Kab. Batu Bara",
    "Pemerintah Kab. Bekasi",
    "Pemerintah Kab. Belitung",
    "Pemerintah Kab. Belitung Timur",
    "Pemerintah Kab. Belu",
    "Pemerintah Kab. Bener Meriah",
    "Pemerintah Kab. Bengkalis",
    "Pemerintah Kab. Bengkayang",
    "Pemerintah Kab. Bengkulu Selatan",
    "Pemerintah Kab. Bengkulu Tengah",
    "Pemerintah Kab. Bengkulu Utara",
    "Pemerintah Kab. Berau",
    "Pemerintah Kab. Biak Numfor",
    "Pemerintah Kab. Bima",
    "Pemerintah Kab. Bintan",
    "Pemerintah Kab. Bireuen",
    "Pemerintah Kab. Blitar",
    "Pemerintah Kab. Blora",
    "Pemerintah Kab. Bojonegoro",
    "Pemerintah Kab. Bolaang Mongondow",
    "Pemerintah Kab. Bolaang Mongondow Selatan",
    "Pemerintah Kab. Bolaang Mongondow Timur",
    "Pemerintah Kab. Bolaang Mongondow Utara",
    "Pemerintah Kab. Bombana",
    "Pemerintah Kab. Bondowoso",
    "Pemerintah Kab. Bone",
    "Pemerintah Kab. Bone Bolango",
    "Pemerintah Kab. Booven Digoel",
    "Pemerintah Kab. Boyolali",
    "Pemerintah Kab. Brebes",
    "Pemerintah Kab. Buleleng",
    "Pemerintah Kab. Bulukumba",
    "Pemerintah Kab. Bulungan",
    "Pemerintah Kab. Bungo",
    "Pemerintah Kab. Buol",
    "Pemerintah Kab. Buru",
    "Pemerintah Kab. Buru Selatan",
    "Pemerintah Kab. Buton",
    "Pemerintah Kab. Buton Selatan",
    "Pemerintah Kab. Buton Tengah",
    "Pemerintah Kab. Buton Utara",
    "Pemerintah Kab. Ciamis",
    "Pemerintah Kab. Cianjur",
    "Pemerintah Kab. Cilacap",
    "Pemerintah Kab. Cirebon",
    "Pemerintah Kab. Dairi",
    "Pemerintah Kab. Deiyai",
    "Pemerintah Kab. Deli Serdang",
    "Pemerintah Kab. Demak",
    "Pemerintah Kab. Dharmasraya",
    "Pemerintah Kab. Dogiyai",
    "Pemerintah Kab. Dompu",
    "Pemerintah Kab. Donggala",
    "Pemerintah Kab. Empat Lawang",
    "Pemerintah Kab. Ende",
    "Pemerintah Kab. Enrekang",
    "Pemerintah Kab. Fak-Fak",
    "Pemerintah Kab. Flores Timur",
    "Pemerintah Kab. Garut",
    "Pemerintah Kab. Gayo Lues",
    "Pemerintah Kab. Gianyar",
    "Pemerintah Kab. Gorontalo",
    "Pemerintah Kab. Gorontalo Utara",
    "Pemerintah Kab. Gowa",
    "Pemerintah Kab. Gresik",
    "Pemerintah Kab. Grobogan",
    "Pemerintah Kab. Gunung Kidul",
    "Pemerintah Kab. Gunung Mas",
    "Pemerintah Kab. Halmahera Barat",
    "Pemerintah Kab. Halmahera Selatan",
    "Pemerintah Kab. Halmahera Tengah",
    "Pemerintah Kab. Halmahera Timur",
    "Pemerintah Kab. Halmahera Utara",
    "Pemerintah Kab. Hulu Sungai Selatan",
    "Pemerintah Kab. Hulu Sungai Tengah",
    "Pemerintah Kab. Hulu Sungai Utara",
    "Pemerintah Kab. Humbang Hasundutan",
    "Pemerintah Kab. Indragiri Hilir",
    "Pemerintah Kab. Indragiri Hulu",
    "Pemerintah Kab. Indramayu",
    "Pemerintah Kab. Intan Jaya",
    "Pemerintah Kab. Jayapura",
    "Pemerintah Kab. Jayawijaya",
    "Pemerintah Kab. Jember",
    "Pemerintah Kab. Jembrana",
    "Pemerintah Kab. Jeneponto",
    "Pemerintah Kab. Jepara",
    "Pemerintah Kab. Jombang",
    "Pemerintah Kab. Kaimana",
    "Pemerintah Kab. Kampar",
    "Pemerintah Kab. Kapuas",
    "Pemerintah Kab. Kapuas Hulu",
    "Pemerintah Kab. Karanganyar",
    "Pemerintah Kab. Karangasem",
    "Pemerintah Kab. Karawang",
    "Pemerintah Kab. Karimun",
    "Pemerintah Kab. Karo",
    "Pemerintah Kab. Katingan",
    "Pemerintah Kab. Kaur",
    "Pemerintah Kab. Kayong Utara",
    "Pemerintah Kab. Kebumen",
    "Pemerintah Kab. Kediri",
    "Pemerintah Kab. Keerom",
    "Pemerintah Kab. Kendal",
    "Pemerintah Kab. Kepahiang",
    "Pemerintah Kab. Kepulauan Anambas",
    "Pemerintah Kab. Kepulauan Aru",
    "Pemerintah Kab. Kepulauan Mentawai",
    "Pemerintah Kab. Kepulauan Meranti",
    "Pemerintah Kab. Kepulauan Sangihe",
    "Pemerintah Kab. Kepulauan Selayar",
    "Pemerintah Kab. Kepulauan Siau Tagulandang Biaro",
    "Pemerintah Kab. Kepulauan Sula",
    "Pemerintah Kab. Kepulauan Talaud",
    "Pemerintah Kab. Kepulauan Tanimbar",
    "Pemerintah Kab. Kepulauan Yapen",
    "Pemerintah Kab. Kerinci",
    "Pemerintah Kab. Ketapang",
    "Pemerintah Kab. Klaten",
    "Pemerintah Kab. Klungkung",
    "Pemerintah Kab. Kolaka",
    "Pemerintah Kab. Kolaka Timur",
    "Pemerintah Kab. Kolaka Utara",
    "Pemerintah Kab. Konawe",
    "Pemerintah Kab. Konawe Kepulauan",
    "Pemerintah Kab. Konawe Selatan",
    "Pemerintah Kab. Konawe Utara",
    "Pemerintah Kab. Kotabaru",
    "Pemerintah Kab. Kotawaringin Barat",
    "Pemerintah Kab. Kotawaringin Timur",
    "Pemerintah Kab. Kuantan Singingi",
    "Pemerintah Kab. Kubu Raya",
    "Pemerintah Kab. Kudus",
    "Pemerintah Kab. Kulon Progo",
    "Pemerintah Kab. Kuningan",
    "Pemerintah Kab. Kupang",
    "Pemerintah Kab. Kutai Barat",
    "Pemerintah Kab. Kutai Kartanegara",
    "Pemerintah Kab. Kutai Timur",
    "Pemerintah Kab. Labuhanbatu",
    "Pemerintah Kab. Labuhanbatu Selatan",
    "Pemerintah Kab. Labuhanbatu Utara",
    "Pemerintah Kab. Lahat",
    "Pemerintah Kab. Lamandau",
    "Pemerintah Kab. Lamongan",
    "Pemerintah Kab. Lampung Barat",
    "Pemerintah Kab. Lampung Selatan",
    "Pemerintah Kab. Lampung Tengah",
    "Pemerintah Kab. Lampung Timur",
    "Pemerintah Kab. Lampung Utara",
    "Pemerintah Kab. Landak",
    "Pemerintah Kab. Langkat",
    "Pemerintah Kab. Lanny Jaya",
    "Pemerintah Kab. Lebak",
    "Pemerintah Kab. Lebong",
    "Pemerintah Kab. Lembata",
    "Pemerintah Kab. Lingga",
    "Pemerintah Kab. Lombok Barat",
    "Pemerintah Kab. Lombok Tengah",
    "Pemerintah Kab. Lombok Timur",
    "Pemerintah Kab. Lombok Utara",
    "Pemerintah Kab. Lumajang",
    "Pemerintah Kab. Luwu",
    "Pemerintah Kab. Luwu Timur",
    "Pemerintah Kab. Luwu Utara",
    "Pemerintah Kab. Madiun",
    "Pemerintah Kab. Magelang",
    "Pemerintah Kab. Magetan",
    "Pemerintah Kab. Mahakam Ulu",
    "Pemerintah Kab. Majalengka",
    "Pemerintah Kab. Majene",
    "Pemerintah Kab. Malaka",
    "Pemerintah Kab. Malang",
    "Pemerintah Kab. Malinau",
    "Pemerintah Kab. Maluku Barat Daya",
    "Pemerintah Kab. Maluku Tengah",
    "Pemerintah Kab. Maluku Tenggara",
    "Pemerintah Kab. Mamasa",
    "Pemerintah Kab. Mamberamo Raya",
    "Pemerintah Kab. Mamberamo Tengah",
    "Pemerintah Kab. Mamuju",
    "Pemerintah Kab. Mamuju Tengah",
    "Pemerintah Kab. Mandailing Natal",
    "Pemerintah Kab. Manggarai",
    "Pemerintah Kab. Manggarai Barat",
    "Pemerintah Kab. Manggarai Timur",
    "Pemerintah Kab. Manokwari",
    "Pemerintah Kab. Manokwari Selatan",
    "Pemerintah Kab. Mappi",
    "Pemerintah Kab. Maros",
    "Pemerintah Kab. Maybrat",
    "Pemerintah Kab. Melawi",
    "Pemerintah Kab. Mempawah",
    "Pemerintah Kab. Merangin",
    "Pemerintah Kab. Merauke",
    "Pemerintah Kab. Mesuji",
    "Pemerintah Kab. Mimika",
    "Pemerintah Kab. Minahasa",
    "Pemerintah Kab. Minahasa Selatan",
    "Pemerintah Kab. Minahasa Tenggara",
    "Pemerintah Kab. Minahasa Utara",
    "Pemerintah Kab. Mojokerto",
    "Pemerintah Kab. Morowali",
    "Pemerintah Kab. Morowali Utara",
    "Pemerintah Kab. Muara Enim",
    "Pemerintah Kab. Muaro Jambi",
    "Pemerintah Kab. Mukomuko",
    "Pemerintah Kab. Muna",
    "Pemerintah Kab. Muna Barat",
    "Pemerintah Kab. Murung Raya",
    "Pemerintah Kab. Musi Banyuasin",
    "Pemerintah Kab. Musi Rawas",
    "Pemerintah Kab. Musi Rawas Utara",
    "Pemerintah Kab. Nabire",
    "Pemerintah Kab. Nagan Raya",
    "Pemerintah Kab. Nagekeo",
    "Pemerintah Kab. Natuna",
    "Pemerintah Kab. Nduga",
    "Pemerintah Kab. Ngada",
    "Pemerintah Kab. Nganjuk",
    "Pemerintah Kab. Ngawi",
    "Pemerintah Kab. Nias",
    "Pemerintah Kab. Nias Barat",
    "Pemerintah Kab. Nias Selatan",
    "Pemerintah Kab. Nias Utara",
    "Pemerintah Kab. Nunukan",
    "Pemerintah Kab. Ogan Ilir",
    "Pemerintah Kab. Ogan Komering Ilir",
    "Pemerintah Kab. Ogan Komering Ulu",
    "Pemerintah Kab. Ogan Komering Ulu Selatan",
    "Pemerintah Kab. Ogan Komering Ulu Timur",
    "Pemerintah Kab. Pacitan",
    "Pemerintah Kab. Padang Lawas",
    "Pemerintah Kab. Padang Lawas Utara",
    "Pemerintah Kab. Padang Pariaman",
    "Pemerintah Kab. Pakpak Bharat",
    "Pemerintah Kab. Pamekasan",
    "Pemerintah Kab. Pandeglang",
    "Pemerintah Kab. Pangandaran",
    "Pemerintah Kab. Pangkajene Dan Kepulauan",
    "Pemerintah Kab. Paniai",
    "Pemerintah Kab. Parimo (Parigi Moutong)",
    "Pemerintah Kab. Pasaman",
    "Pemerintah Kab. Pasaman Barat",
    "Pemerintah Kab. Paser",
    "Pemerintah Kab. Pasuruan",
    "Pemerintah Kab. Pati",
    "Pemerintah Kab. Pegunungan Arfak",
    "Pemerintah Kab. Pegunungan Bintang",
    "Pemerintah Kab. Pekalongan",
    "Pemerintah Kab. Pelalawan",
    "Pemerintah Kab. Pemalang",
    "Pemerintah Kab. Penajam Paser Utara",
    "Pemerintah Kab. Penukal Abab Lematang Ilir",
    "Pemerintah Kab. Pesawaran",
    "Pemerintah Kab. Pesisir Barat",
    "Pemerintah Kab. Pesisir Selatan",
    "Pemerintah Kab. Pidie",
    "Pemerintah Kab. Pidie Jaya",
    "Pemerintah Kab. Pinrang",
    "Pemerintah Kab. Pohuwato",
    "Pemerintah Kab. Polewali Mandar",
    "Pemerintah Kab. Ponorogo",
    "Pemerintah Kab. Pontianak",
    "Pemerintah Kab. Pontianak (Mempawah)",
    "Pemerintah Kab. Poso",
    "Pemerintah Kab. Pringsewu",
    "Pemerintah Kab. Probolinggo",
    "Pemerintah Kab. Pulang Pisau",
    "Pemerintah Kab. Pulau Morotai",
    "Pemerintah Kab. Pulau Taliabu",
    "Pemerintah Kab. Puncak",
    "Pemerintah Kab. Puncak Jaya",
    "Pemerintah Kab. Purwakarta",
    "Pemerintah Kab. Purworejo",
    "Pemerintah Kab. Raja Ampat",
    "Pemerintah Kab. Rejang Lebong",
    "Pemerintah Kab. Rembang",
    "Pemerintah Kab. Rokan Hilir",
    "Pemerintah Kab. Rokan Hulu",
    "Pemerintah Kab. Rote Ndao",
    "Pemerintah Kab. Sabu Raijua",
    "Pemerintah Kab. Salatiga",
    "Pemerintah Kab. Sambas",
    "Pemerintah Kab. Samosir",
    "Pemerintah Kab. Sampang",
    "Pemerintah Kab. Sanggau",
    "Pemerintah Kab. Sarmi",
    "Pemerintah Kab. Sarolangun",
    "Pemerintah Kab. Secang",
    "Pemerintah Kab. Seh",
    "Pemerintah Kab. Selayar",
    "Pemerintah Kab. Seluma",
    "Pemerintah Kab. Semarang",
    "Pemerintah Kab. Seram Bagian Barat",
    "Pemerintah Kab. Seram Bagian Timur",
    "Pemerintah Kab. Serang",
    "Pemerintah Kab. Serdang Bedagai",
    "Pemerintah Kab. Seruyan",
    "Pemerintah Kab. Siak",
    "Pemerintah Kab. Sidenreng Rappang",
    "Pemerintah Kab. Sidoarjo",
    "Pemerintah Kab. Sigi",
    "Pemerintah Kab. Sijunjung",
    "Pemerintah Kab. Sikka",
    "Pemerintah Kab. Simalungun",
    "Pemerintah Kab. Simeulue",
    "Pemerintah Kab. Singkawang",
    "Pemerintah Kab. Sinjai",
    "Pemerintah Kab. Sintang",
    "Pemerintah Kab. Situbondo",
    "Pemerintah Kab. Sleman",
    "Pemerintah Kab. Solok",
    "Pemerintah Kab. Solok Selatan",
    "Pemerintah Kab. Soppeng",
    "Pemerintah Kab. Sorong",
    "Pemerintah Kab. Sorong Selatan",
    "Pemerintah Kab. Sragen",
    "Pemerintah Kab. Subang",
    "Pemerintah Kab. Sukabumi",
    "Pemerintah Kab. Sukamara",
    "Pemerintah Kab. Sukoharjo",
    "Pemerintah Kab. Sumba Barat",
    "Pemerintah Kab. Sumba Barat Daya",
    "Pemerintah Kab. Sumba Tengah",
    "Pemerintah Kab. Sumba Timur",
    "Pemerintah Kab. Sumbawa",
    "Pemerintah Kab. Sumbawa Barat",
    "Pemerintah Kab. Sumedang",
    "Pemerintah Kab. Sumenep",
    "Pemerintah Kab. Supiori",
    "Pemerintah Kab. Tabalong",
    "Pemerintah Kab. Tabanan",
    "Pemerintah Kab. Takalar",
    "Pemerintah Kab. Tambrauw",
    "Pemerintah Kab. Tana Tidung",
    "Pemerintah Kab. Tana Toraja",
    "Pemerintah Kab. Tanah Bumbu",
    "Pemerintah Kab. Tanah Datar",
    "Pemerintah Kab. Tanah Laut",
    "Pemerintah Kab. Tangerang",
    "Pemerintah Kab. Tanggamus",
    "Pemerintah Kab. Tanjung Jabung Barat",
    "Pemerintah Kab. Tanjung Jabung Timur",
    "Pemerintah Kab. Tapanuli Selatan",
    "Pemerintah Kab. Tapanuli Tengah",
    "Pemerintah Kab. Tapanuli Utara",
    "Pemerintah Kab. Tapin",
    "Pemerintah Kab. Tarakan",
    "Pemerintah Kab. Tasikmalaya",
    "Pemerintah Kab. Tebing Tinggi",
    "Pemerintah Kab. Tebo",
    "Pemerintah Kab. Teluk Bintuni",
    "Pemerintah Kab. Teluk Wondama",
    "Pemerintah Kab. Temanggung",
    "Pemerintah Kab. Timor Tengah Selatan",
    "Pemerintah Kab. Timor Tengah Utara",
    "Pemerintah Kab. Toba Samosir",
    "Pemerintah Kab. Tojo Una-Una",
    "Pemerintah Kab. Tolitoli",
    "Pemerintah Kab. Tolikara",
    "Pemerintah Kab. Tomohon",
    "Pemerintah Kab. Toraja Utara",
    "Pemerintah Kab. Trenggalek",
    "Pemerintah Kab. Tual",
    "Pemerintah Kab. Tuban",
    "Pemerintah Kab. Tulang Bawang",
    "Pemerintah Kab. Tulang Bawang Barat",
    "Pemerintah Kab. Tulungagung",
    "Pemerintah Kab. Wajo",
    "Pemerintah Kab. Wakatobi",
    "Pemerintah Kab. Waropen",
    "Pemerintah Kab. Way Kanan",
    "Pemerintah Kab. Wonogiri",
    "Pemerintah Kab. Wonosobo",
    "Pemerintah Kab. Yahukimo",
    "Pemerintah Kab. Yalimo",
    "Pemerintah Kota Ambon",
    "Pemerintah Kota Balikpapan",
    "Pemerintah Kota Banda Aceh",
    "Pemerintah Kota Bandar Lampung",
    "Pemerintah Kota Bandung",
    "Pemerintah Kota Banjar",
    "Pemerintah Kota Banjarbaru",
    "Pemerintah Kota Banjarmasin",
    "Pemerintah Kota Batam",
    "Pemerintah Kota Batu",
    "Pemerintah Kota Bau-Bau",
    "Pemerintah Kota Bekasi",
    "Pemerintah Kota Bengkulu",
    "Pemerintah Kota Bima",
    "Pemerintah Kota Binjai",
    "Pemerintah Kota Bitung",
    "Pemerintah Kota Blitar",
    "Pemerintah Kota Bogor",
    "Pemerintah Kota Bontang",
    "Pemerintah Kota Bukittinggi",
    "Pemerintah Kota Cilegon",
    "Pemerintah Kota Cimahi",
    "Pemerintah Kota Cirebon",
    "Pemerintah Kota Denpasar",
    "Pemerintah Kota Depok",
    "Pemerintah Kota Dumai",
    "Pemerintah Kota Gorontalo",
    "Pemerintah Kota Gunungsitoli",
    "Pemerintah Kota Jakarta Barat",
    "Pemerintah Kota Jakarta Pusat",
    "Pemerintah Kota Jakarta Selatan",
    "Pemerintah Kota Jakarta Timur",
    "Pemerintah Kota Jakarta Utara",
    "Pemerintah Kota Jambi",
    "Pemerintah Kota Jayapura",
    "Pemerintah Kota Kediri",
    "Pemerintah Kota Kendari",
    "Pemerintah Kota Kotamobagu",
    "Pemerintah Kota Kupang",
    "Pemerintah Kota Langsa",
    "Pemerintah Kota Lhokseumawe",
    "Pemerintah Kota Lubuklinggau",
    "Pemerintah Kota Madiun",
    "Pemerintah Kota Magelang",
    "Pemerintah Kota Makassar",
    "Pemerintah Kota Malang",
    "Pemerintah Kota Manado",
    "Pemerintah Kota Mataram",
    "Pemerintah Kota Medan",
    "Pemerintah Kota Metro",
    "Pemerintah Kota Mojokerto",
    "Pemerintah Kota Padang",
    "Pemerintah Kota Padangpanjang",
    "Pemerintah Kota Padangsidimpuan",
    "Pemerintah Kota Pagar Alam",
    "Pemerintah Kota Palangka Raya",
    "Pemerintah Kota Palembang",
    "Pemerintah Kota Palopo",
    "Pemerintah Kota Palu",
    "Pemerintah Kota Pangkal Pinang",
    "Pemerintah Kota Parepare",
    "Pemerintah Kota Pariaman",
    "Pemerintah Kota Pasuruan",
    "Pemerintah Kota Payakumbuh",
    "Pemerintah Kota Pekalongan",
    "Pemerintah Kota Pekanbaru",
    "Pemerintah Kota Pematangsiantar",
    "Pemerintah Kota Pontianak",
    "Pemerintah Kota Prabumulih",
    "Pemerintah Kota Probolinggo",
    "Pemerintah Kota Sabang",
    "Pemerintah Kota Salatiga",
    "Pemerintah Kota Samarinda",
    "Pemerintah Kota Sawahlunto",
    "Pemerintah Kota Semarang",
    "Pemerintah Kota Serang",
    "Pemerintah Kota Sibolga",
    "Pemerintah Kota Singkawang",
    "Pemerintah Kota Solok",
    "Pemerintah Kota Sorong",
    "Pemerintah Kota Subulussalam",
    "Pemerintah Kota Sukabumi",
    "Pemerintah Kota Sungai Penuh",
    "Pemerintah Kota Surabaya",
    "Pemerintah Kota Surakarta",
    "Pemerintah Kota Tangerang",
    "Pemerintah Kota Tangerang Selatan",
    "Pemerintah Kota Tanjung Balai",
    "Pemerintah Kota Tanjung Pinang",
    "Pemerintah Kota Tarakan",
    "Pemerintah Kota Tasikmalaya",
    "Pemerintah Kota Tebing Tinggi",
    "Pemerintah Kota Tegal",
    "Pemerintah Kota Ternate",
    "Pemerintah Kota Tidore Kepulauan",
    "Pemerintah Kota Tomohon",
    "Pemerintah Kota Tual",
    "Pemerintah Kota Yogyakarta"
]

def slugify(text):
    text = text.lower()
    text = re.sub(r'[(]', '-', text)
    text = re.sub(r'[)]', '', text)
    text = re.sub(r'[^a-z0-9]+', '-', text)
    text = re.sub(r'(^-|-$)', '', text)
    return text

def categorize(name):
    if name.startswith("Kementerian"): return "MINISTRY"
    if "Provinsi" in name: return "PROVINCE"
    if "Kota" in name: return "CITY"
    if "Kab." in name: return "REGENCY"
    if any(k in name for k in ["Badan", "Lembaga", "Sekretariat", "Otoritas", "Kejaksaan", "Kepolisian"]): return "AGENCY"
    return "OTHER"

data = []
seen_ids = set()

for name in institution_names:
    item_id = slugify(name)
    if item_id not in seen_ids:
        data.append({
            "id": item_id,
            "name": name,
            "category": categorize(name)
        })
        seen_ids.add(item_id)

with open('c:/Users/user/Documents/GitHub/procurify-bm/sveltekit/src/lib/data/klpd.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Successfully generated klpd.json with {len(data)} institutions.")
